version: '3'
services:
  datatools:
    image: betagouv/datatools:fix_graphql_spec
    ports:
    - "4000:4000"
    volumes:
    - ./data:/data
    depends_on:
    - postgres
    - mongo

  postgres:
    image: postgres
    restart: always
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=user
    - POSTGRES_DB=catalogue
    volumes:
    - pgdata:/var/lib/postgresql/data
    
  mongo:
    image: mongo
    volumes:
    - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
